### ISSUE TITLE
Gif's in the Readme file is not showing up correctly

### ISSUE THREAD

**Issue by serdaraglamis** [irfansimsar/videojs-viewability#4]
For example;

https://raw.githubusercontent.com/irfansimsar/videojs-viewability/master/docs/demo-video-1.gif @serdaraglamis

**Comment by serdaraglamis** [comment]
@irfansimsar  I think they are working fine for me. Does this problem still occur?

**Comment by irfansimsar** [comment]
@serdaraglamis problem solved, I think it was related to server cache.
